### PR TITLE
Completed css-canvas-medical - Tam Nguyen

### PR DESCRIPTION
**Pull request by tam-n**
image

### CODE REVIEW

**Review by shawnkost — CHANGES_REQUESTED** [review]
Hey Tam! Please include screenshots of all the other sections, or a short video of you scrolling down the page

**Comment by tam-n** [comment]
image
image

**Review by shawnkost — CHANGES_REQUESTED** [review]
Code looks good Tam! Just a couple changes requested here!

1. The image should be aligned with the canvas logo. So the image should start in the same spot the logo does.
2. There should be less whitespace between the image and the "Clinicians Prefer Canvas" section

**Comment by tam-n** [comment]
image
image

**Review by shawnkost — APPROVED** [review]
Nice job Tam! 👍🏻

**Pull request merged**
